repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
        stages: [commit]
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
        stages: [commit]
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
        stages: [commit]
      - id: check-yaml # checks yaml files for parseable syntax.
        stages: [commit]
      - id: detect-private-key # detects the presence of private keys.
        stages: [commit]
      - id: mixed-line-ending # replaces or checks mixed line ending.
        stages: [commit]
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
        stages: [commit]
      - id: trailing-whitespace # trims trailing whitespace.
        stages: [commit]
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0
    hooks:
      - id: check-github-actions
        stages: [commit]
      - id: check-github-workflows
        stages: [commit]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        stages: [commit]
      # Run the formatter.
      - id: ruff-format
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini, --install-types, --non-interactive]
        exclude: "tests"
        stages: [push]