repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.116
    hooks:
      - id: ruff
  # --- This is so tedious to get working that I'm leaving it to a next PR; it does not simulate local mypy at all ---
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.931"
  #   hooks:
  #     - id: mypy
  #       args: [--follow-imports=skip, --config-file=mypy.ini, --install-types, --non-interactive, --verbose]
  #       exclude: "tests"