RunConfig:
  mode: LICHESS # running mode, choose from: LICHESS, UCI

SearcherConfig:
  max_depth: 6 # maximum depth for negamax search
  search_mode: SINGLE_PROCESS # mode of search, choice of: SINGLE_PROCESS, LAZY_SMP
  move_order_mode: MVV_LVA # mode of move ordering, choice of: MVV_LVA (only)
  enable_null_move_pruning: True # flag to enable null move pruning, i.e. checking for a beta-cutoff by passing our turn
  enable_delta_pruning: True # flag to enable delta pruning, i.e. prune capturing moves that do not raise alpha in quiescence search.
  enable_transposition_table: False # flag to enable position cache, so positions are not evaluated twice
  enable_aspiration_windows: True # flag to enable aspiration windows, i.e. doing a smaller window search around the score from previous iteration of iterative deepening.

# Current time management strategy is alloted_move_time = time_weight * current_time + increment_weight * increment
TimeManagerConfig:
  time_weight: 0.1 
  increment_weight: 0.01

OpeningBookConfig:
  opening_book_path: data/opening.bin # path to opening_book binary 

LoggingConfig:
  version: 1
  formatters:
    detailed:
      format: '[%(levelname)s][%(asctime)s] %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: detailed
  root:
    level: DEBUG
    handlers: ['console']

