name: Dev

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  setup_and_run_tests:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
      # -- Setup --
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write API_TOKEN to file
        run: echo -n "$API_TOKEN" >> api_token.txt
        shell: bash
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      # -- Docker build --
      - name: Build Docker image
        run: docker build -t sporkfish-dev .
      # -- Code checking (don't know how to separate these atm) --
      - name: Code checks
        run: |
            docker run sporkfish-dev
            pytest -sv
            mypy --install-types --non-interactive
            black --check .
            isort --check --profile black .
        
     
      