name: Dev

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  setup_and_run_tests:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
      # -- Setup --
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write API_TOKEN to file
        run: echo -n "$API_TOKEN" >> api_token.txt
        shell: bash
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      # -- Docker build --
      - name: Build Docker image
        run: docker build -t sporkfish-dev .
      # -- Code checking --
      - name: Run docker container
        run: docker run -d -it sporkfish-dev
      - name: Static type checks (mypy)
        run: docker exec sporkfish-dev mypy --install-types --non-interactive
      - name: Run tests (pytest)
        run: docker exec sporkfish-dev pytest -sv
      - name: Check code format (black)
        run: docker exec sporkfish-dev black --check .
      - name: Check imports format (isort)
        run: docker exec sporkfish-dev isort --check --profile black .
        
     
      